@startuml
class Card {
    - money: int
    + getAmount(): int
    + subtract(amount)
    + addMoney(amount)
}

class Wallet {
    - cards: Card[]
    - cash: int
    + getCards(): Card[]
    + getCashAmount(): int
    + subtractCash(amount)
    + addCash(amount)
}
Wallet *-- Card: has

class Phone {
    - number
    - notifications[]
    + constructor(number: string)
    + getNumber(): string
    + pushNotification(notification)
    + getNotifications(): Notification[]
}
Phone o-- Notification: receives

class Person {
    - person
    - firstName: string
    - lastName: string
    - wallet: Wallet
    - phone: Phone
    + constructor(firstName, lastName)

    + getFirstName(): string
    + getLastName(): string
    + getWallet(): Wallet
    + getPhone(): Phone

    + reserveTable(branch, period, table?)
    + takeTable(table)
    + makeOrder(items)
    + freeTable()
}
Person *-- Phone: has
Person *-- Wallet: has

class Waiter extends Employee {
    + makeOrder(table, items)
    + getBill(table): Bill
    + getMenu(): Menu
}
Waiter ..> ReservationsList: serves orders

class Receptionist extends Employee {
    + getFreeTables(period): Table[]
    + getReservedTable(person): Table | null
    + reserve(person, table, period)
}
Receptionist ..> ReservationsList: manges reservations

class Chef extends Employee {
    + cookOrder(order): Meals[]
}

class Employee {
    - restaurant: Branch
    + constructor(restaurant)
    + getRestaurant(): Branch
}

class Manager extends Employee {
    + addTable(seatsNum: int)
    + removeTable(table)

    + addMeal(sectionName, product)
    + removeMeal(meal)

    + supplyProduct(productType, weight)

    + createManager(person)
    + createReceptionist(person)
    + createWaiter(person)
}
<> management
management ..> Storage: manages products
management ..> Menu: manages sections & itmes
management ..> TablesList: manages tables
Manager .. management: manages

abstract class Notification {
    - person: Person
    # constructor(person)
    + {abstract} getText(): string
    + sent()
}

class ReservationNotification extends Notification {
    + constructor(person, reservation)
    + getText(): string
}

enum ProductType {
    + meat
    + water
    + bread
    + milk
    + vegetable
}

class Product {
    - type: ProductType
    - weight: int
    + constructor(type, weight)
    + getType(): ProductType
    + getWeight(): int
}
ProductType -* Product: has

class Storage {
    - products: Set<type, Product>
    + getProducts(): Product[]
    + getProduct(type): Product
    + addProduct(type, weight)
    + removeProduct(type, weigh)
}
Storage o-- Product: keeps

abstract Meal {
    - products: Set<Product>
    - price: int
    + constructor(products, price)
    + getProducts(): Product[]
    + setProducts(products)
    + setPrice(price)
}
Meal *-- Product: includes

class Dish extends Meal {
}

class Drink extends Meal {
}

class Section {
    - name: string
    - meals: Set<Meal>
    + getName(): string
    + getMeals()
    + addMeal(meal)
    + removeMeal(meal)
}
Section o-- Meal: includes

class Menu {
    - sections: Set<Section>
    + getSections(): Section[]
    + addSection(section)
    + removeSection()
}
Menu *-- Section: has

class Seat {
    - person: Person | null
    + take(person)
    + free()
}

class Table {
    - seats: Seat[]
    - meals: Meal[]
    + addSeat(seat)
    + removeSeat(seat)
    + getSeats(): Seat[]

    + addMeal(meal)
    + getMeals(): Meal[]
}
Table *-- Seat: has

class TablesList {
    - tables: Set<Table>
    + getTables()
    + addTable(table)
    + removeTable(table)
}
TablesList o-- Table: manages

enum PaymentStatus {
    + Pending
    + Payed
}

abstract Payment {
    - amount
    + constructor(amount)
    + {abstract} pay()
}
Payment *- PaymentStatus: has
Payment -- Bill: of

class CardPayment extends Payment {
    + pay(card)
}

class CashPayment extends Payment {
    + pay(wallet)
}

class Item {
    - meal: Meal
    - quantity: int
    + constructor(meal, quantity)
    + getCost(): int
}

class Bill {
    - amount: int
    - payment: Payment | null
    + pay(payment)
    + isPayed()
}

class Order {
    - table: Table
    - items: Item
    + addItem(meal, quantity)
    + getCoast(): int
}
Order o-- Item: includes

class Period {
    - start: DateTime
    - end: DateTime
    + constructor(start, end)

    + getStartTime(): DateTime
    + setStartTime(start)

    + getEndTime(): DateTime
    + setEndTime(end)
}

enum ReservationStatus {
    + Pending
    + Active
    + Done
}

class Reservation {
    - status: ReservationStatus
    - person: Person
    - table: Table
    - period: Period
    - orders: Order[]
    - bill: Bill | null
    + constructor(person, table, period)

    + getPerson(): Person

    + getTable(): TablesList
    + setTable(table)

    + getPeriod(): Period
    + setPeriod(period)

    + getOrders(): Order[]
    + addOrder(order)

    + makeBill(): Bill
    + cancel()
    + isActive(): bool
}
Reservation *- ReservationStatus: has
Reservation o-- Person: assigned to
Reservation o-- Table: reserved place
Reservation o-- Period: has
Reservation o-- Order: has
Reservation *-- Bill: has / produces

class ReservationsList {
    - reservations: Set<Reservation>
    - tables: TablesList
    + getReservations(): Reservation[]
    + getPersonActiveReservation(person): Reservation | null
    + getTableActiveReservation(table): Reservation | null

    + reserve(Person, Table, Period): Reservation

    + getFreeTables(period): Table[]
}
ReservationsList o-- Reservation: manages
ReservationsList ..> TablesList: use
note left of ReservationsList::getPersonActiveReservation
for receptionist
endnote
note left of ReservationsList::getTableActiveReservation
for waiter
endnote

class Address {
    - country: string
    - state: string
    - city: string
    - streetAddress: string
    - zipCode: string
    + constructor(country, state, city, streetAddress, zipCode)
    + getCountry(): string
    + getState(): string
    + getCity(): string
    + getStreetAddress(): string
    + getZipCode(): string
}

class Branch {
    - address: Address
    - storage: Storage
    - menu: Menu
    - tables: TablesList
    - reservations: ReservationsList
    - managers: Manager[]
    - receptionists: Receptionist[]
    - waiters: Waiters[]

    + getManagers(): Manager[]
    + addManager(manger)

    + getReceptionists(): Reservation[]
    + addReceptionist(receptionist)

    + getWaiters(): Waiter[]
    + addWaiter(waiter)

    + getStorage()
    + getMenu()
    + getTablesList(): TablesList

    + informOfReservations()
}
Branch *-- Address: located at
Branch -- Employee: has / belongs
Branch *-- Storage: has
Branch *-- Menu: has
Branch *-- TablesList: has
Branch *-- ReservationsList: has

class Restaurant {
    - restaurants: Set<Branch>
    + getBranches(): Branch[]
    + addBranch(branch)
    + removeRestaurant(branch)
}
Restaurant *-- Branch: has

class System <<Singleton>> {
    - restaurants: Restaurant[]
    + getRestaurants(): Restaurant
}
System o-- Restaurant: provides

'TODO
' - chef
'TODO: Scheduling, reports

@enduml
